[gateway.config]
port = 9090

# Global plugins
[[gateway.config.requestPlugins]]
id = "AddHeadersPlugin"
config = {appId = "xyz-app"}

[[gateway.config.responsePlugins]]
id = "RemoveHeadersPlugin"
config = {appId = "xyz-app"}

[gateway.config.pluginProperties]
access-token-buffer-time = "900000"
client-id = "ZwsAB4FFH6vUHqMlLprElsmgjq8a"
client-secret = "c4nwkM9_jET5mBC5xYitPK9nd6Ma"
internal-ip-class = "10"
nxn-resource-cache-url = "https://xxxxx.net/"
oauth-service-url = "https://api.asgardeo.io/t/hahack23"
omni-url = "https://xxxxx"
orchestration-service-url = "https://xxx"
proxy-ips = "170.61.236.0,170.61.236.1,170.61.236.6,170.61.236.7"
rp-url = "https://xxxx"

# Application 1 
[[gateway.config.apps]]
basePath = "/app/nxn-resource-cache"
endpointUrl = "https://run.mocky.io/v3/34a9aeba-0b71-4fac-8451-b122c50cce45"

[[gateway.config.apps.requestPlugins]]
id = "AddAccessTokenPlugin"

# Application 2
[[gateway.config.apps]]
basePath = "/api/nxn-navbar-service"
endpointUrl = "https://run.mocky.io/v3/8f5cd8a1-85ae-4d73-946b-59dda7ce5992"

[[gateway.config.apps.requestPlugins]]
id = "CORSHeaderPlugin"

[[gateway.config.apps.requestPlugins]]
id = "NetworkControlPlugin"
config = {level = "2"}

[[gateway.config.apps.requestPlugins]]
id = "AddAccessTokenPlugin"

# Application 3
[[gateway.config.apps]]
basePath = "/api/nxn-entitlement-service"
endpointUrl = "https://run.mocky.io/v3/6613f69c-65cf-44d4-b29c-7887f21cfd59"

[[gateway.config.apps.requestPlugins]]
id = "NetworkControlPlugin"
config = {level = "2"}

[[gateway.config.apps.requestPlugins]]
id = "AddAccessTokenPlugin"

# Application 4
[[gateway.config.apps]]
basePath = "/api/nxn-entitlement-service/metrics"
endpointUrl = "https://run.mocky.io/v3/b6a301fc-64d8-497d-9138-058d8946bd70"

# Application 5
[[gateway.config.apps]]
basePath = "/api/npx-service"
endpointUrl = "https://run.mocky.io/v3/84643c67-6ddb-4cf1-8141-f637154c9520"

# Application 6
[[gateway.config.apps]]
basePath = "/api"
endpointUrl = "https://run.mocky.io/v3/34a9aeba-0b71-4fac-8451-b122c50cce45"